CREATE TABLE IF NOT EXISTS role(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users(
    userID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    pass VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    roleID INT NOT NULL DEFAULT 1,
    phoneNumber VARCHAR(40) NOT NULL,
    companyName VARCHAR(50),
    locatedIn VARCHAR(50),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (roleID) REFERENCES role(id)
);

CREATE TABLE IF NOT EXISTS truck(
    truckID INT AUTO_INCREMENT PRIMARY KEY,
    currentLocation VARCHAR(50) NOT NULL,
    truckType VARCHAR(50) NOT NULL,
    dateAvailable DATE NOT NULL,
    maxWeight INT NOT NULL,
    vanLength VARCHAR(20),
    width VARCHAR(20),
    booked BOOLEAN DEFAULT FALSE,
    userID INT NOT NULL,
    FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS freight(
    freightID INT AUTO_INCREMENT PRIMARY KEY,
    currentLocation VARCHAR(50) NOT NULL,
    destination VARCHAR(50) NOT NULL,
    truckType VARCHAR(50) NOT NULL,
    dateAvailable DATE NOT NULL,
    maxWeight INT NOT NULL,
    booked BOOLEAN DEFAULT FALSE,
    full BOOLEAN DEFAULT TRUE,
    userID INT NOT NULL,
    FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO role (name) VALUES
('user'),
('admin')
ON DUPLICATE KEY UPDATE name=name;